<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge;chrome=1">
    <meta name="renderer" content="webkit">
    <title>我就是TM要用ES6,让IE8见鬼去吧</title>
    <script src="./dist/babel.min.js"></script>
    <script src="./dist/polyfill.js"></script>
</head>
<body>
    <div></div>
    <div></div>
    <div></div>
    <script type="text/babel">
        console.log(`
一般来说，不要在then方法里面定义 Reject 状态的回调函数（即then的第二个参数），
总是使用catch方法。

// bad
promise
  .then(function(data) {
    // success
  }, function(err) {
    // error
  });

// good
promise
  .then(function(data) { //cb
    // success
  })
  .catch(function(err) {
    // error
  });

  跟传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，
  Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。

  一般总是建议，Promise 对象后面要跟catch方法，这样可以处理 Promise 内部发生的错误。
  catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法。
`)
        const someAsyncThing = function() {
            return new Promise(function(resolve, reject) {
                // 下面一行会报错，因为x没有声明
                resolve(x + 2);
            });
        };

        someAsyncThing().then(function() {
            console.log('everything is great');
        });

        setTimeout(() => { console.log(123) }, 2000);
    </script>
</body>
</html>